version: '3.9'
services:
  db:
    image: postgres
    container_name: company_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: company_db
    ports:
      - "5434:5432"