version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"